name: CP4MCM Workflow

on:
  push:
    branches:
      - main

jobs:
  CP4MCM-Workflow:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
       
      - name: Validae Payload 
        run: |
          sudo wget https://raw.githubusercontent.com/mukesh9467/cp4mcm/main/main.tf -O /var/tmp/tf12/main.tf
          terraform init 
          terraform plan
          sudo /var/tmp/tf12/terraform apply --auto-approve 
