name: Setup Terraform Engine

on:
  push:
    branches:
      - main

jobs:
  launch-ec2:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
       
      # Setup & configure instance
      - name: Configure Intance
        run: |
          sudo cd /var/tmp/tf12/
          sudo wget https://raw.githubusercontent.com/mukesh9467/cp4mcm/main/main.tf

