name: Setup Terraform Engine

on:
  push:
    branches:
      - main

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Launch an EC2 instance & extarct public IP
      - name: Launch EC2 instance
        run: 
          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-092da15d79485517f --instance-type t2.micro --key-name tf_key --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=CP4MCM}]' --query 'Instances[0].InstanceId' --output text)
          
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
      
          echo "Public IP - $PUBLIC_IP"
