name: Validate Payload Stage

on:
  push:
    branches:
      - main

jobs:
  Validate-Payload:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
       
      - name: Terraform 
        run: |
          sudo wget https://raw.githubusercontent.com/mukesh9467/cp4mcm/main/main.tf -O /var/tmp/tf12/main.tf
          cd /var/tmp/tf12 ; terraform init
          cd /var/tmp/tf12 ; terraform plan
          cd /var/tmp/tf12 ; sudo /var/tmp/tf12/terraform apply --auto-approve 
