name: Setup Terraform Engine

on:
  push:
    branches:
      - main

jobs:
  CP4MCM:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
       
      # Setup & configure instance
      - name: Downloa
        run: |
          cd /var/tmp/tf12/
          sudo wget https://raw.githubusercontent.com/mukesh9467/cp4mcm/main/main.tf -O /var/tmp/tf12/main.tf

