name: Setup Terraform Engine

on:
  push:
    branches:
      - main

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Launch an EC2 instance & extract public IP
      - name: Launch EC2 Instance
        id: launch_ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-092da15d79485517f --instance-type t2.micro --key-name tf_key --security-group-ids sg-0826493edff1d99c8 --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=CP4MCM}] --ouput text')
          echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV
          
      - name: Wait for Instance to be Running
        run:
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}
          #INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=image-id,Values=ami-092da15d79485517f" "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[].[InstanceId]' --output text | tail -n 1)   
          #echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV
          
      - name: Extract Public IP of Instance
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --query 'Reservations[*].Instances[0].PublicIpAddress' --output text)
          echo "Public IP: $PUBLIC_IP"
