name: CP4MCM Workflow

on:
  push:
    branches:
      - main

jobs:
  CP4MCM:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
       
      - name: Validate Payload-1
        run: sudo wget https://raw.githubusercontent.com/mukesh9467/cp4mcm/main/main.tf -O /var/tmp/tf12/main.tf
          
      - name: Run Terraform Plan
        run: |
          sudo /var/tmp/tf12/terraform init /var/tmp/tf12
          cd /var/tmp/tf12
          sudo ./terraform plan

