name: Launch EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Launch an EC2 instance
      - name: Launch EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-053b12d3152c0cc71 \
            --instance-type t2.micro \
            --key-name tf_key \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MyEC2Instance}]'
